enableGlobalCache: false

plugins:
  - checksum: 4eaf4d5cb875c1f65f1fccb8624d29a3ed2842170c924ba645e034b9f295bee0aee6f0a8a0dd17f7b64c39f83d988422316885e88c6f4a01bba561481cfc2a35
    path: .yarn/plugins/@yarnpkg/plugin-repack.cjs
    spec: yarn-plugin/bundles/@yarnpkg/plugin-repack.js

yarnPath: .yarn/releases/yarn-remote.cjs
