enableGlobalCache: false

plugins:
  - checksum: e39f49d5ead1a95506f27b1004def318097568166452dfd8e612fe296933827986b709df84902cba41de23c89c5cb8ae0aba172a99c1c2e01fc70fd4039bfcdc
    path: .yarn/plugins/@yarnpkg/plugin-repack.cjs
    spec: "https://raw.githubusercontent.com/LIMPIX31/plugin-repack/master/yarn-plugin/bundles/@yarnpkg/plugin-repack.js"

yarnPath: .yarn/releases/yarn-remote.cjs
